version: "3.7"
services:
  php:
    network_mode: bridge
    build:
      context: .
    volumes:
      - ./src:/src
    ports:
      - 8040:8000
    links:
      - mysql-db:db
  mysql-db:
    ports:
      - 8083:3306
    network_mode: bridge
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./src/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: priority_queue
  swagger:
    image: swaggerapi/swagger-ui
    network_mode: bridge
    ports:
      - 8085:8080
    volumes:
      - ./docs/swagger:/usr/share/nginx/html/definitions
    environment:
      API_URL: definitions/swagger.yml
