version: "3.7"
services:
  php:
    network_mode: bridge
    build:
      context: .
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    links:
      - mysql-db:db
  mysql-db:
    ports:
      - 8083:3306
    network_mode: bridge
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./src/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: priority_queue